
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aditi
 */
public class Currencycoverter1 extends javax.swing.JFrame {

    /**
     * Creates new form Currencycoverter1
     */
    public Currencycoverter1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        Convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Enter the Amount");

        jLabel2.setText("From");

        jLabel3.setText("To");

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Srilankan Rupees", "Indian Rupees", "Nepali Rupees", "Australian Dollar", " ", " " }));

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Srilankan Rupees", "Indian Rupees", "USD", "Nepali Rupees", "Australian Dollar", " " }));

        Convert.setText("Convert");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtamount)
                    .addComponent(txtfrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtto, 0, 175, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Convert)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        Double tot;
        Double amount=Double.parseDouble(txtamount.getText());
        
        if(txtfrom.getSelectedItem().toString()=="USD" && txtto.getSelectedItem().toString()=="Srilankan Rupees")
        {
            tot=amount * 334.27;
            JOptionPane.showMessageDialog(this, " Your Amount Will be "+tot.toString());
            
        }
        else if(txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString()== "Indian Rupees")
        {
                tot=amount * 82.54;
                JOptionPane.showMessageDialog(this, "Your Amount Will Be " +tot.toString());
                   
         }
        
       else  if(txtfrom.getSelectedItem().toString() == "USD" && txtto.getSelectedItem().toString() == "Nepali Rupees")
        {
            tot = amount * 130.29;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        } 
        
       else  if(txtfrom.getSelectedItem().toString() == "USD" && txtto.getSelectedItem().toString() == "Australian Dollar")
        {
            tot = amount * 1.49;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }   
        
         else  if(txtfrom.getSelectedItem().toString() == "USD" && txtto.getSelectedItem().toString() == "USD")
        {
            tot = amount;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
       
        
       
        
            
         else  if(txtfrom.getSelectedItem().toString() == "Srilankan Rupees" && txtto.getSelectedItem().toString() == "Indian Rupees")
        {
            tot = amount *0.25;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
         else  if(txtfrom.getSelectedItem().toString() == "Srilankan Rupees" && txtto.getSelectedItem().toString() == "Nepali Rupees")
        {
            tot = amount *0.39;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
         else  if(txtfrom.getSelectedItem().toString() == "Srilankan Rupees" && txtto.getSelectedItem().toString() == "Australian Dollar")
        {
            tot = amount *0.0045;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
          else  if(txtfrom.getSelectedItem().toString() == "Srilankan Rupees" && txtto.getSelectedItem().toString() == "USD")
        {
            tot = amount *0.0030;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
          
           else  if(txtfrom.getSelectedItem().toString() == "Srilankan Rupees" && txtto.getSelectedItem().toString() == "Srilankan Rupees")
        {
            tot = amount;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
          
          
        
           else  if(txtfrom.getSelectedItem().toString() == "Indian Rupees" && txtto.getSelectedItem().toString() == "USD")
        {
            tot = amount *0.012;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }   
        
         else  if(txtfrom.getSelectedItem().toString() == "Indian Rupees" && txtto.getSelectedItem().toString() == "Srilankan Rupees")
        {
            tot = amount * 3.9;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }   
        
        
        else  if(txtfrom.getSelectedItem().toString() == "Indian Rupees" && txtto.getSelectedItem().toString() == "Nepali Rupees")
        {
            tot = amount *1.60;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }   
        
        
        else  if(txtfrom.getSelectedItem().toString() == "Indian Rupees" && txtto.getSelectedItem().toString() == "Australian Dollar")
        {
            tot = amount * 0.018;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
         else  if(txtfrom.getSelectedItem().toString() == "Indian Rupees" && txtto.getSelectedItem().toString() == "Indian Rupees")
        {
            tot = amount;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }   
        
        
        else  if(txtfrom.getSelectedItem().toString() == "Nepali Rupees" && txtto.getSelectedItem().toString() == "USD")
        {
            tot = amount *0.0076;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
        
        else  if(txtfrom.getSelectedItem().toString() == "Nepali Rupees" && txtto.getSelectedItem().toString() == "Indian Rupees")
        {
            tot = amount *0.63;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
        
        else  if(txtfrom.getSelectedItem().toString() == "Nepali Rupees" && txtto.getSelectedItem().toString() == "Australian Dollar")
        {
            tot = amount *0.011;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
        
        else  if(txtfrom.getSelectedItem().toString() == "Nepali Rupees" && txtto.getSelectedItem().toString() == "Srilankan Rupees")
        {
            tot = amount *2.44;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
         else  if(txtfrom.getSelectedItem().toString() == "Nepali Rupees" && txtto.getSelectedItem().toString() == "Nepali Rupees")
        {
            tot = amount;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }  
        
        
        
         else  if(txtfrom.getSelectedItem().toString() == "Australian Dollar" && txtto.getSelectedItem().toString() == "USD")
        {
            tot = amount *0.68;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
         else  if(txtfrom.getSelectedItem().toString() == "Australian Dollar" && txtto.getSelectedItem().toString() == "Indian Rupees")
        {
            tot = amount *55.22;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
         else  if(txtfrom.getSelectedItem().toString() == "Australian Dollar" && txtto.getSelectedItem().toString() == "Nepali Rupees")
        {
            tot = amount *88.34;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
         else  if(txtfrom.getSelectedItem().toString() == "Australian Dollar" && txtto.getSelectedItem().toString() == "Srilankan Rupees")
        {
            tot = amount *215.59;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
        else  if(txtfrom.getSelectedItem().toString() == "Australian Dollar" && txtto.getSelectedItem().toString() == "Australian Dollar")
        {
            tot = amount;
            JOptionPane.showMessageDialog(this, "Your Amount will be " + tot.toString());
        }    
        
        
        
        
        
        
        
    }//GEN-LAST:event_ConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currencycoverter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currencycoverter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currencycoverter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currencycoverter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currencycoverter1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
